services:
    - docker:dind

stages:
    - build
    - test
    - deploy

build:website:
    image: registry.gitlab.com/ldso18-19/t5g2:website
    stage: build
    artifacts:
        untracked: true
    script:
        - cd Website
        - composer install

build:feup-8:
    image: registry.gitlab.com/ldso18-19/t5g2:feup-8
    stage: build
    artifacts:
        untracked: true
    script:
        - cd FEUP-8
        - cmake .
        - make -j4

test:website:
    image: registry.gitlab.com/ldso18-19/t5g2:website
    stage: test
    dependencies:
        - build:website
    script:
        - pecl install xdebug-2.6.0
        - docker-php-ext-enable xdebug
        - cd Website
        - touch database/database_tests.sqlite
        - APP_ENV=testing php artisan migrate:refresh
        - APP_ENV=testing php artisan passport:install
        - cd database
        - sqlite3 database_tests.sqlite < database_tests_data.sql
        - cd ..
        - APP_ENV=testing ./vendor/bin/phpunit --testdox
    artifacts:
        paths:
            - ./Website/report

pages:
  stage: deploy
  dependencies:
    - test:website
  script:
    - mv ./Website/report public/
  artifacts:
    paths:
      - public
    expire_in: 30 days


test:feup-8:
    image: registry.gitlab.com/ldso18-19/t5g2:feup-8
    stage: test
    dependencies:
        - build:feup-8
    script:
        - cd FEUP-8/bin
        - ./tic80 -test

deploy:website:
    image: registry.gitlab.com/ldso18-19/t5g2:website
    stage: deploy
    script:
        - cd Website
    environment:
        name: production
    when: manual
    only:
        - master
